blank_issues_enabled: false
contact_links:
  - name: BetterDiscord Support Server
    url: https://discordz.xyz/invite
    about: The best place to get immediate support.
  - name: Troubleshooting Guide
    url: https://docs.discordz.xyz/users/getting-started/troubleshooting
    about: The user troubleshooting guide from the documentation.